-- 仮置き：本番にだけある未使用テーブル（どの SQL でも作られていない）。
-- 本当の定義はタスク4の本番ダンプで確認する。ここでは migration-5/6 を通すための空テーブル。
create table if not exists public.books (id bigint generated by default as identity primary key);
create table if not exists public.users (id bigint generated by default as identity primary key);
alter table public.books enable row level security;
alter table public.users enable row level security;
