import type { Listing, Reservation, User } from "./types";

// ===================================================
// モックデータ層
// 後で Supabase 等のデータソースへ差し替える「継ぎ目」。
// UI は必ずこのモジュール経由でデータを取得する。
// ===================================================

export const mockUsers: User[] = [
  {
    id: "user_001",
    name: "田中 蓮",
    email: "tanaka@glomac.ac.jp",
    university: "GLOMAC大学",
    faculty: "工学部",
    grade: "3年",
    rating: 4.8,
    rating_count: 12,
  },
  {
    id: "user_002",
    name: "佐藤 葵",
    email: "sato@glomac.ac.jp",
    university: "GLOMAC大学",
    faculty: "経済学部",
    grade: "2年",
    rating: 5.0,
    rating_count: 7,
  },
  {
    id: "user_003",
    name: "山本 海斗",
    email: "yamamoto@glomac.ac.jp",
    university: "GLOMAC大学",
    faculty: "文学部",
    grade: "4年",
    rating: 4.6,
    rating_count: 21,
  },
];

const DAY = 24 * 60 * 60 * 1000;
const now = 1_780_000_000_000; // 固定のベース時刻（モックの再現性のため）

export const mockListings: Listing[] = [
  {
    id: "listing_001",
    title: "線形代数入門 第3版",
    subject: "線形代数学",
    author: "田中一郎",
    isbn: "978-4-00000001",
    publication_year: "2022",
    description: "書き込みはほとんどありません。章末問題の一部に鉛筆メモあり。",
    condition: "書き込み少し",
    price: 800,
    location: "正門前",
    seller_id: "user_001",
    seller_name: "田中 蓮",
    status: "出品中",
    views: 42,
    likes: 5,
    created_at: now - 1 * DAY,
  },
  {
    id: "listing_002",
    title: "ミクロ経済学の力",
    subject: "ミクロ経済学",
    author: "神取道宏",
    isbn: "978-4-00000002",
    publication_year: "2021",
    description: "とても綺麗な状態です。カバーあり。",
    condition: "書き込みなし",
    price: 1800,
    location: "中央図書館前",
    seller_id: "user_002",
    seller_name: "佐藤 葵",
    status: "出品中",
    views: 88,
    likes: 11,
    created_at: now - 2 * DAY,
  },
  {
    id: "listing_003",
    title: "総合英語 Forest 7th",
    subject: "英語I",
    author: "石黒昭博",
    isbn: "978-4-00000003",
    publication_year: "2020",
    description: "マーカー多めですが本文は読めます。",
    condition: "書き込み少し",
    price: 500,
    location: "駅前カフェ",
    seller_id: "user_003",
    seller_name: "山本 海斗",
    status: "出品中",
    views: 30,
    likes: 2,
    created_at: now - 3 * DAY,
  },
  {
    id: "listing_004",
    title: "物理学基礎 第2版",
    subject: "物理学概論",
    author: "原康夫",
    isbn: "978-4-00000004",
    publication_year: "2019",
    description: "新品同様。授業を取らなくなったため出品します。",
    condition: "新品・未使用",
    price: 2400,
    location: "理工学部棟前",
    seller_id: "user_001",
    seller_name: "田中 蓮",
    status: "出品中",
    views: 65,
    likes: 9,
    created_at: now - 4 * DAY,
  },
  {
    id: "listing_005",
    title: "マクロ経済学",
    subject: "マクロ経済学",
    author: "二神孝一",
    isbn: "978-4-00000005",
    publication_year: "2023",
    description: "表紙に少し折れがあります。",
    condition: "汚れ・ダメージあり",
    price: 1200,
    location: "学生会館前",
    seller_id: "user_002",
    seller_name: "佐藤 葵",
    status: "予約済み",
    views: 120,
    likes: 14,
    created_at: now - 5 * DAY,
  },
  {
    id: "listing_006",
    title: "プログラミング言語C 第2版",
    subject: "情報処理基礎",
    author: "B.W.カーニハン",
    isbn: "978-4-00000006",
    publication_year: "2018",
    description: "名著。書き込みなし。",
    condition: "書き込みなし",
    price: 1500,
    location: "正門前",
    seller_id: "user_003",
    seller_name: "山本 海斗",
    status: "出品中",
    views: 51,
    likes: 6,
    created_at: now - 6 * DAY,
  },
  {
    id: "listing_007",
    title: "統計学入門",
    subject: "基礎統計学",
    author: "東京大学教養学部",
    isbn: "978-4-00000007",
    publication_year: "2017",
    description: "赤本でおなじみの統計入門。",
    condition: "書き込み少し",
    price: 1000,
    location: "中央図書館前",
    seller_id: "user_001",
    seller_name: "田中 蓮",
    status: "完了",
    views: 200,
    likes: 18,
    created_at: now - 7 * DAY,
  },
  {
    id: "listing_008",
    title: "フランス語初級文法",
    subject: "第二外国語（仏）",
    author: "六鹿豊",
    isbn: "978-4-00000008",
    publication_year: "2022",
    description: "未使用に近いです。",
    condition: "新品・未使用",
    price: 900,
    location: "語学棟前",
    seller_id: "user_002",
    seller_name: "佐藤 葵",
    status: "出品中",
    views: 22,
    likes: 1,
    created_at: now - 8 * DAY,
  },
];

export const mockReservations: Reservation[] = [
  {
    id: "res_001",
    listing_id: "listing_005",
    listing_title: "マクロ経済学",
    buyer_id: "user_001",
    buyer_name: "田中 蓮",
    seller_id: "user_002",
    seller_name: "佐藤 葵",
    price: 1200,
    preferred_date: "2026-06-10",
    preferred_time: "昼頃（12:00〜14:00）",
    preferred_location: "学生会館前",
    message: "マクロ経済学の授業で使います。よろしくお願いします。",
    status: "申請中",
    created_at: now - 1 * DAY,
  },
  {
    id: "res_002",
    listing_id: "listing_007",
    listing_title: "統計学入門",
    buyer_id: "user_002",
    buyer_name: "佐藤 葵",
    seller_id: "user_001",
    seller_name: "田中 蓮",
    price: 1000,
    preferred_date: "2026-06-05",
    preferred_time: "午後（14:00〜18:00）",
    preferred_location: "中央図書館前",
    message: "",
    status: "完了",
    created_at: now - 6 * DAY,
  },
];

export function getListings(): Listing[] {
  return mockListings;
}

export function getListingById(id: string): Listing | undefined {
  return mockListings.find((l) => l.id === id);
}

export function getUserById(id: string): User | undefined {
  return mockUsers.find((u) => u.id === id);
}
